# NumPy Array Operations

This notebook creates a NumPy array with 24 elements and demonstrates `reshape()`, `flatten()`, `ravel()`, and transpose.

In [1]:
import numpy as np

# Create a one-dimensional NumPy array containing 24 elements
arr = np.arange(1, 25)
print("Original 1D array:\n", arr)

# reshape(): change the array's dimensions without changing its data
matrix = arr.reshape(4, 6)
print("\nReshaped to 4 x 6:\n", matrix)

# flatten(): return a one-dimensional COPY of the array
flattened = matrix.flatten()
print("\nflatten() result:\n", flattened)

# ravel(): return a one-dimensional VIEW when possible
ravelled = matrix.ravel()
print("\nravel() result:\n", ravelled)

# transpose (or matrix.T): swap rows and columns
transposed = matrix.transpose()
print("\nTransposed array (6 x 4):\n", transposed)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshaped to 4 x 6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

flatten() result:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

ravel() result:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Transposed array (6 x 4):
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


## `flatten()` vs. `ravel()`

- `flatten()` **always creates a copy**. Changes made to its result do not affect the original array.
- `ravel()` returns a **view whenever possible**, so changing its result can change the original array. If a view is not possible (for example, with certain non-contiguous arrays), it creates a copy instead.

Use `flatten()` when you need an independent array; use `ravel()` when you prefer lower memory use and can work with a possible view.

In [2]:
# Verify the copy-versus-view behavior
example = np.arange(1, 7).reshape(2, 3)
flat_copy = example.flatten()
ravel_view = example.ravel()

flat_copy[0] = 100
ravel_view[1] = 200

print("Original after modifying flatten() and ravel() results:\n", example)
print("\nflatten() result (independent copy):", flat_copy)
print("ravel() result (view here):", ravel_view)

Original after modifying flatten() and ravel() results:
 [[  1 200   3]
 [  4   5   6]]

flatten() result (independent copy): [100   2   3   4   5   6]
ravel() result (view here): [  1 200   3   4   5   6]
