# NumPy Array Indexing and Slicing

This notebook creates a 5×5 NumPy array and demonstrates common ways to access its values. NumPy uses zero-based indexing: the first row and column have index `0`.

In [1]:
import numpy as np

# Create a 5×5 array containing the values 1 to 25.
array_5x5 = np.arange(1, 26).reshape(5, 5)
array_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Positive indexing
`array_5x5[1, 2]` selects the item at row index `1` and column index `2` (the second row, third column).

In [2]:
positive_index = array_5x5[1, 2]
positive_index

8

## Negative indexing
Negative indices count backward from the end. `array_5x5[-1, -2]` selects the last row and second-last column.

In [3]:
negative_index = array_5x5[-1, -2]
negative_index

24

## Slicing
`array_5x5[1:4, 1:4]` takes rows with indices `1` through `3` and columns with indices `1` through `3`. The stop index (`4`) is excluded.

In [4]:
sliced_array = array_5x5[1:4, 1:4]
sliced_array

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## Row selection
`array_5x5[2, :]` selects every column (`:`) from row index `2`, which is the third row.

In [5]:
third_row = array_5x5[2, :]
third_row

array([11, 12, 13, 14, 15])

## Column selection
`array_5x5[:, 3]` selects every row (`:`) from column index `3`, which is the fourth column.

In [6]:
fourth_column = array_5x5[:, 3]
fourth_column

array([ 4,  9, 14, 19, 24])

## Extracting a submatrix
`array_5x5[1:4, 2:5]` extracts a 3×3 submatrix using rows `1`–`3` and columns `2`–`4`.

In [7]:
submatrix = array_5x5[1:4, 2:5]
submatrix

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])