# Creating NumPy Arrays

This notebook demonstrates common NumPy functions for creating arrays and explains when each one is useful.

In [1]:
import numpy as np

# Set a seed so the random example is reproducible.
np.random.seed(42)

## Differences between array-creation methods

- `np.array()` converts existing data (such as a Python list or tuple) into a NumPy array.
- `np.zeros()` creates an array of a chosen shape filled with `0`.
- `np.ones()` creates an array of a chosen shape filled with `1`.
- `np.full()` creates an array of a chosen shape filled with any value you specify.
- `np.eye()` creates a 2-D identity matrix: ones on the main diagonal and zeros elsewhere.
- `np.arange()` creates evenly spaced values using a start, stop, and step; the stop value is excluded.
- `np.linspace()` creates a specified number of evenly spaced values between two endpoints; by default, both endpoints are included.
- `np.random` generates arrays containing random values, useful for sampling, simulations, and test data.

In [2]:
# 1. array(): create an array from existing Python data
from_list = np.array([10, 20, 30, 40])

# 2. zeros(): fill an array with zeros
zero_array = np.zeros((2, 3))

# 3. ones(): fill an array with ones
one_array = np.ones((2, 3))

# 4. full(): fill an array with a chosen value
filled_array = np.full((2, 3), 7)

# 5. eye(): create an identity matrix
identity_matrix = np.eye(3)

# 6. arange(): values at a fixed interval (stop is excluded)
range_array = np.arange(0, 10, 2)

# 7. linspace(): a fixed number of values between endpoints
linear_array = np.linspace(0, 10, 6)

# 8. random: random decimal values from 0 (inclusive) to 1 (exclusive)
random_array = np.random.random((2, 3))

print('np.array():\n', from_list)
print('\nnp.zeros():\n', zero_array)
print('\nnp.ones():\n', one_array)
print('\nnp.full():\n', filled_array)
print('\nnp.eye():\n', identity_matrix)
print('\nnp.arange():\n', range_array)
print('\nnp.linspace():\n', linear_array)
print('\nnp.random.random():\n', random_array)

np.array():
 [10 20 30 40]

np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]]

np.full():
 [[7 7 7]
 [7 7 7]]

np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.arange():
 [0 2 4 6 8]

np.linspace():
 [ 0.  2.  4.  6.  8. 10.]

np.random.random():
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


### Key distinction: `arange()` vs. `linspace()`

Use `arange(start, stop, step)` when you know the spacing between values. Use `linspace(start, stop, num)` when you know how many values you want, including the endpoints by default.